platform :ios, '9.0'

target 'armFirebase' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for armFirebase

  target 'armFirebase-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'armFirebaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Database', '~> 5.11.0'

end

